In [14]:
! pip install pandas 
import pandas as pd

class NoronMcCulloch:
  def __init__(self):
    self._denderits = []
    self._summitionValue = 0

  def addDenderit(self,value,weight):
    self._denderits.append({
        value:value,
        weight:weight
    })
    self._summitionValue += value*weight
  def makeNose(self,activitionFucntion):
    return activitionFucntion(self._summitionValue);
  def getSum(self):
    return self._summitionValue

threshHolds = [1.5,-2.5,1,-1.5,0]
weightMatrix = [
    [2,-3,1,0],
    [-2,-2,-2,-2],
    [2,-1,1.5,-5],
    [1,1,1,1],
    [0.5,-0.5,0,-1],
]
data = []
for threshHold,weights in zip(threshHolds,weightMatrix):
  record = {} 
  for i in range(16):
    bits = f'{i:04b}'

    noron = NoronMcCulloch();

    noron.addDenderit(int(bits[0]),weights[0]);
    noron.addDenderit(int(bits[1]),weights[1]);
    noron.addDenderit(int(bits[2]),weights[2]);
    noron.addDenderit(int(bits[3]),weights[3]);

    isFeasible = noron.makeNose(lambda x: x>threshHold)

    record[i] = isFeasible;
  data.append(record)

df = pd.DataFrame(data,index=[
    str(weightMatrix[0])+','+str(threshHolds[0]),
    str(weightMatrix[1])+','+str(threshHolds[1]),
    str(weightMatrix[2])+','+str(threshHolds[2]),
    str(weightMatrix[3])+','+str(threshHolds[3]),
    str(weightMatrix[4])+','+str(threshHolds[4]),
]);
df.to_csv('out.csv')
display(df)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2022.2.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
"[2, -3, 1, 0],1.5",False,False,False,False,False,False,False,False,True,True,True,True,False,False,False,False
"[-2, -2, -2, -2],-2.5",True,True,True,False,True,False,False,False,True,False,False,False,False,False,False,False
"[2, -1, 1.5, -5],1",False,False,True,False,False,False,False,False,True,False,True,False,False,False,True,False
"[1, 1, 1, 1],-1.5",True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
"[0.5, -0.5, 0, -1],0",False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False